### ISSUE TITLE
Mejorar diálogos ingreso de datos

### ISSUE THREAD

**Issue by augusticor** [augusticor/PseudoRandomNumberGenerator#2]
#### Arreglar algunas cosas del commit fe6b283

- Eliminar la acción "exit" de el enum de acciones, ya que no tenemos botón de salir, no es necesaria.
- Igual en el controller eliminar la acción en switch
- Crear los objetos de los diálogos como variables globales privadas en la clase MainWindow, para reutilizarlos, ya que actualmente esta creando un objeto por cada vez que los muestra
- Modificar la clase en el paquete runner para llamar "new Control();" y se inicie la aplicación.
- Disminuir el ancho de los diálogos e iniciar el texto con letra mayúscula.
- Cambiar el color de los botones en los diálogos a el mismo color de los botones de la MainWindow, los colores están en la clase "MyConstants".

**Comment by Richardagudelo** [comment]
los objetos de las clases JDialog se instanciaron directamente en el control.

**Comment by augusticor** [comment]
👍🏽👍🏽

**Comment by augusticor** [comment]
9f7a29c
