### ISSUE TITLE
arreglar métodos faltantes para el envió de información desde los JD

### ISSUE THREAD

**Issue by Richardagudelo** [augusticor/PseudoRandomNumberGenerator#3]
Tareas
- [x] Realizar el método en el JDialog
- [x] Realizar el método fachada en el PseudoMainWindows 
- [x]  Pedir el método en el controlador

**Comment by augusticor** [comment]
Mis metodos ya ee2bd57

**Comment by Richardagudelo** [comment]
tareas realizadas
